In [ ]:
Name:- Rajratna Vijay Bhosale
Roll NO:- 23091003
Class:- MSc I Year

**Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the
random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its
Row Echelon Form by performing elementary row operations.**

In [2]:
import numpy as np


np.random.seed(3)  


A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)

def row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    break
        matrix[[i, r]] = matrix[[r, i]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(m):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] = matrix[i] - lv * matrix[r]
        lead += 1
    return matrix

row_echelon_A = row_echelon_form(A.copy())
print("\nRow Echelon Form of Matrix A:")
print(row_echelon_A)


Matrix A:
[[8 9 3 8 8]
 [0 5 3 9 9]
 [5 7 6 0 4]
 [7 8 1 6 2]
 [2 1 3 5 8]]

Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
